
namespace EventStreamDotNet
{
    /// <summary>
    /// Defines how the library updates the domain model snapshot stored in the database.
    /// </summary>
    public enum SnapshotFrequencyEnum
    {
        /// <summary>
        /// A snapshot is never generated by the event stream manager. Some external source
        /// may do this (based on event projection handlers, for example).
        /// </summary>
        Never = 0,

        /// <summary>
        /// The snapshot is always updated after all posted events are successfully stored.
        /// This is the fastest way to ensure the snapshot is synchronized with the event stream.
        /// </summary>
        AfterAllEvents = 1,

        /// <summary>
        /// The snapshot is updated after each posted event is successfully stored. This can be
        /// much slower than <see cref="AfterAllEvents"/> if many events are posted in a batch.
        /// </summary>
        AfterEachEvent = 2,

        /// <summary>
        /// The SnapshotInterval configuration value indicates the number of deltas after which
        /// a new snapshot is generated.
        /// </summary>
        AfterIntervalDeltas = 3,

        /// <summary>
        /// The SnapshotInterval configuration value indicates the number of seconds after which
        /// a new snapshot is generated. There is no automated timer, an additional delta must be
        /// written before an expired duration will be recognized.
        /// </summary>
        AfterIntervalSeconds = 4,
    }
}
