
namespace EventStreamDotNet
{
    public enum SnapshotFrequencyEnum
    {
        /// <summary>
        /// A snapshot is never generated by the event stream manager. Some external source
        /// may do this (based on event projection handlers, for example).
        /// </summary>
        Never = 0,

        /// <summary>
        /// The snapshot is always updated after all posted events are successfully stored.
        /// This is the fastest way to ensure the snapshot is synchronized with the event stream.
        /// </summary>
        AfterAllEvents = 1,

        /// <summary>
        /// The snapshot is updated after each posted event is successfully stored. This can be
        /// much slower than <see cref="AfterAllEvents"/> if many events are posted in a batch.
        /// </summary>
        AfterEachEvent = 2,

        /// <summary>
        /// The snapshot is updated after <em>at least</em> ten events are posted. If a batch of
        /// events are posted, all events will be stored before the snapshot is updated.
        /// </summary>
        Countdown10Events = 3,

        /// <summary>
        /// The snapshot is updated after <em>at least</em> one hundred events are posted. If a batch of
        /// events are posted, all events will be stored before the snapshot is updated.
        /// </summary>
        Countdown100Events = 4,

        /// <summary>
        /// The snapshot is updated after <em>at least</em> one second has passed since the last snapshot.
        /// The snapshot will not update automatically, after the duration expires, posting a new event will
        /// trigger the snapshot update.
        /// </summary>
        Duration1Second = 5,

        /// <summary>
        /// The snapshot is updated after <em>at least</em> ten seconds have passed since the last snapshot.
        /// The snapshot will not update automatically, after the duration expires, posting a new event will
        /// trigger the snapshot update.
        /// </summary>
        Duration10Seconds = 6,

        /// <summary>
        /// The snapshot is updated after <em>at least</em> one minute has passed since the last snapshot.
        /// The snapshot will not update automatically, after the duration expires, posting a new event will
        /// trigger the snapshot update.
        /// </summary>
        Duration1Minute = 7
    }
}
